#include "four_in_a_row/fiar.hpp"
#include "maze/maze.hpp"
#include "mine_sweeper/minesw.hpp"
#include "pacman/pacman.hpp"
#include "snake/snake.hpp"
#include "tetris/tetris.hpp"
#include "tic_tac_toe/ttt.hpp"
